name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Cache deps
        uses: Swatinem/rust-cache@v2

      - name: Install deps
        run: cargo install just dprint

      - name: Lint
        run: just lint

      - name: Check formatting
        run: just fmt-check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Cache deps
        uses: Swatinem/rust-cache@v2

      - name: Install deps
        run: cargo install just dprint

      - name: Build
        run: just build

      - name: Run tests
        run: just test-all
